# Generated by Django 2.1.8 on 2019-04-08 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_link', models.CharField(max_length=2048, unique=True, validators=[django.core.validators.URLValidator()])),
                ('short_link', models.CharField(max_length=2048, unique=True, validators=[django.core.validators.URLValidator()])),
                ('number_of_visits', models.IntegerField(default=0)),
            ],
        ),
    ]
